default: &default
  adapter: postgresql
  encoding: unicode
  username: root
  password: root
  host: localhost
  pool: 5

development:
  <<: *default
  database: pruebaupsa_development

test:
  <<: *default
  database: pruebaupsa_test

production:
  #Configuracion de heroku
  <<: *default
  database: d7cj05eg4he3vb
  username: kvkowenfbfwobi
  password: P3T1vGVFSNqWOITevzWS8NaYtv
